export enum PropertyType {
  APARTMENT = "APARTMENT",
  DUPLEX = "DUPLEX",
  VILLA = "VILLA",
  HOUSE = "HOUSE",
  BUILDING = "BUILDING",
  GROUND = "GROUND",
  BUNGALOW = "BUNGALOW",
  COTTAGE = "COTTAGE",
  FACTORY = "FACTORY",
  RIAD = "RIAD",
  TRIPLEX = "TRIPLEX",
  STUDIO = "STUDIO",
  HANGAR = "HANGAR"
}
